### ISSUE TITLE
你好，请问登录密码是多少？数据库里加密了

### ISSUE THREAD

**Issue by ZainZhao** [lcg0124/clouddo#3]
你好，请问登录密码是多少？数据库里加密了

**Comment by happytobobo** [comment]
111111






------------------ 原始邮件 ------------------
发件人: "Zain"<notifications@github.com>;
发送时间: 2019年6月1日(星期六) 晚上8:10
收件人: "lcg0124/clouddo"<clouddo@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [lcg0124/clouddo] 你好，请问登录密码是多少？数据库里加密了 (#3)




Closed #3.
